# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(blank=True, db_column='Invoice_Number', null=True)),
                ('customer_number', models.CharField(blank=True, db_column='Customer_Number', max_length=100, null=True)),
                ('customer_purchase_order_number', models.IntegerField(blank=True, db_column='Customer_Purchase_Order_Number', null=True)),
                ('doctype', models.IntegerField(blank=True, db_column='DOCTYPE', null=True)),
            ],
        ),
    ]
