# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170719_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code_810',
            options={},
        ),
    ]
