# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170719_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code_810',
        ),
    ]
