# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code_810',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(blank=True, db_column='Invoice_Number', null=True)),
                ('customer_number', models.CharField(blank=True, db_column='Customer_Number', max_length=100, null=True)),
                ('customer_purchase_order_number', models.IntegerField(blank=True, db_column='Customer_Purchase_Order_Number', null=True)),
                ('doctype', models.IntegerField(blank=True, db_column='DOCTYPE', null=True)),
            ],
            options={
                'db_table': 'TEST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Code_856',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(blank=True, db_column='Invoice_Number', null=True)),
                ('customer_number', models.CharField(blank=True, db_column='Customer_Number', max_length=100, null=True)),
                ('customer_purchase_order_number', models.IntegerField(blank=True, db_column='Customer_Purchase_Order_Number', null=True)),
                ('doctype', models.IntegerField(blank=True, db_column='DOCTYPE', null=True)),
            ],
            options={
                'db_table': 'TEST2',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
